#!/usr/bin/env python3
from txt_to_datamodel import load_datamodel_summary, update_datamodel, save_datamodel_yaml
release = 'dr18'
product = 'mos_target'
tables = ["allwise", "carton_to_target", "catalog", "catalog_to_allwise", "catalog_to_catwise2020", "catalog_to_glimpse", "catalog_to_guvcat", "catalog_to_legacy_survey_dr8", "catalog_to_panstarrs1", "catalog_to_sdss_dr13_photoobj_primary", "catalog_to_skies_v2", "catalog_to_skymapper_dr2", "catalog_to_supercosmos", "catalog_to_tic_v8", "catwise2020", "gaia_dr2_ruwe", "gaia_dr2_source", "gaia_unwise_agn", "gaiadr2_tmass_best_neighbour", "geometric_distances_gaia_dr2", "glimpse", "guvcat", "legacy_survey_dr8", "magnitude", "panstarrs1", "sdss_dr13_photoobj_primary", "skies_v2", "skymapper_dr2", "supercosmos", "target", "tic_v8", "twomass_psc", "best_brightest", "bhm_csc_v2", "bhm_efeds_veto", "bhm_rm_v0_2", "cadence", "cadence_epoch", "carton", "cataclysmic_variables", "catalog_to_bhm_efeds_veto", "catalog_to_bhm_rm_v0_2", "catalog_to_sdss_dr16_specobj", "catalog_to_tycho2", "catalog_to_uvotssc1", "catalog_to_xmm_om_suss_4_1", "category", "ebosstarget_v5", "gaia_dr2_wd", "instrument", "mapper", "sagitta", "sdss_apogeeallstarmerge_r13", "sdss_dr16_qso", "sdss_dr16_specobj", "tycho2", "uvotssc1", "xmm_om_suss_4_1", "yso_clustering", "zari18pms"]
for table in tables:
    file = '%s_%s.txt' % (release, table)
    table = '%s_%s' % (product, table)
    datamodel, summary = load_datamodel_summary(release = release, file = file)
    datamodel = update_datamodel(table = table, datamodel = datamodel, summary = summary)
    save_datamodel_yaml(table = table, datamodel = datamodel)


FileExistsError: dr18_bhm_rm_v0_2_1.txt does not exist.
FileExistsError: dr18_catalogdb_version.txt does not exist.
FileExistsError: dr18_targetdb_version.txt does not exist.


